- src/configuration.rs
- src/lib.rs
- src/metrics.rs
This PR:
- add the env label according to [docs](https://playbooks.decentraland.systems/ops/metrics.html#naming-metrics)
> feat: add env label to metrics for prometheus

- src/middlewares/metrics_token.rs
- tests/metrics.rs
this PR: 
- get the metrics token from the authorization header
> fix: get metrics token from headers

- Cargo.lock
- Cargo.toml
- src/components/app.rs
- src/components/redis.rs
- src/components/synapse.rs
- src/components/users_cache.rs
- tests/components/redis.rs
- tests/components/users_cache.rs
This PR:
- replace `mockall` for `faux` crate
It's a variant of PR #76 and closes #74
> tests: try `faux` crate for mocking and testing

- src/components/app.rs
- src/components/synapse.rs
- src/lib.rs
- src/middlewares/check_auth.rs
- src/routes/synapse/handlers.rs
- tests/routes/mod.rs
- tests/routes/synapse.rs
This PR:
- fix Mutex not async-aware
- add `/login` route to sniff synapse logins
- store hashed user access token in Redis cache after `POST /login` (synapse)
> feat: sniff synapse login

- src/entities/friendships.rs
- tests/component_database.rs
Store friendships in lexicographic order in the database, this way always `address_1 <= address_2`
> fix: order addresses in friendships

- src/entities/friendships.rs
- tests/routes/v1/friendships/get.rs
Missing braces made GET /friendships return also inactive
> fix: get friendships query

- src/components/database.rs
- src/entities/friendship_history.rs
- src/entities/friendships.rs
- src/entities/user_features.rs
- src/routes/synapse/room_events.rs
- tests/component_database.rs
This PR:
- refactors the use of the lifetimes for DB `Transaction` in order to make it more flexible and usable in any context. 
Related to what we talk with @Julieta11 on #140
> refactor: improve use of lifetimes

- configuration.toml
- src/api/app.rs
- src/components/app.rs
- src/components/configuration.rs
- src/components/synapse.rs
- src/main.rs
- src/middlewares/check_auth.rs
- src/ports/users_cache.rs
- src/ws/app.rs
- src/ws/service/friendships_service.rs
AppComponents are the components necessary to run the REST server, avoid using it in the RPC Module, so all shared components are now Arc
> refactor: use SocialContext in RPC Server and not AppComponents

- migrations/20230419161219_remove-inactive-friendships-without-history.down.sql
- migrations/20230419161219_remove-inactive-friendships-without-history.up.sql
fixes: https://github.com/decentraland/dservices/issues/61
All friendships that meet all the following criteria are deleted:
- They are inactive
- They do not have a `synapse_room_id`
- They do not have any associated `friendship_history`
This Pull Request contains updates regarding the migration of `synapse_room_id` in the friendships table. The version that runs the migration on the friendships table has been deployed in `.zone`. Upon completion of the migration, it was observed that there are 405,764 friendships with `synapse_room_id`, while 52,921 friendships have `synapse_room_id = NULL`. It was determined that the 50,000 friendships with `NULL synapse_room_id` are inactive and were stored as such during the migration from Synapse to the Social Service. This means that to obtain the …
> feat: remove inactive friendships without history

- Cargo.lock
- Cargo.toml
- src/components/synapse.rs
- src/ws/service/synapse_handler.rs
- Fix `extract_domain` to return `zone` as default.
- Fix `build_room_alias_name` to follow synapse pattern.
- Define CreateRoomOpts preset as String instead of Enum
> fix: `build_room_alias_name` and `extract_domain`

- src/api/routes/synapse/room_events.rs
- src/ws/service/database_handler.rs
- tests/component_database.rs
- Fix: when `room_message_body` is None, the closure passed to the map method will not be executed, and `metadata` will also be None. Now, `metadata` will always be a Json type wrapping a FriendshipMetadata object, even if `room_message_body` is None.
**The API seems to be working because we're getting a blank string in the metadata: `""` (whenever there is no an actual message), so the closure always gets executed.**
> fix: `metadata` None when `room_message_body` None

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/ws/app.rs
- src/ws/service/friendships_service.rs
Changes:
- Bump RPC lib to `2.1.1`
- Added `SocialTransportContext` to `SocialContext` to handle all context specific to a transport
- Added `Address` to `SocialTransportContext` to link `transport_id` to `user_id`
- Remove generators of subscriptions from `SocialContext` when a transport disconnects
Fixes https://github.com/decentraland/social-service/issues/200
> feat: handle transport disconnection

- src/ws/metrics.rs
- src/ws/service/friendships_service.rs
Add the procedure name as a label in the current error metrics, so that it's easier to recognize the source of the error.
```j son
dcl_social_service_rpc_error_response_code { procedure = "GetFriends", status_code = "UNAUTHORIZED" } 1
dcl_social_service_rpc_error_response_code { procedure = "GetRequestEvents", status_code = "UNAUTHORIZED" } 1
dcl_social_service_rpc_error_response_code { procedure = "UpdateFriendshipEvent", status_code = "UNAUTHORIZED" } 2
```
Fixes #213
> feat: add procedure as a label in metrics

- src/ws/service/friendships_service.rs
- src/ws/service/mapper/event.rs
- tests/ws_service_friendship_service.rs
Use the entity's created_at field instead of re-calculating it
Fixes https://github.com/decentraland/social-service/issues/197
> Use consistent created_at

- src/components/synapse.rs
- src/synapse/synapse_handler.rs
- src/ws/app.rs
- src/ws/service/friendship_event_updates.rs
- src/ws/service/friendships_service.rs
- src/ws/service/mapper/payload.rs
- src/ws/transport.rs
- tests/component_database.rs
Fixes #232 
When trying to set the account data for the user sometimes we were getting the error `invalid type: map, expected unit`. I've specified the type we need `HashMap<String, Vec<String>>` when calling the function `authenticated_put_request`
> fix: set account data

- src/entities/queries.rs
fixes: https://github.com/decentraland/social-service/issues/237
> fix: filter only inactive when querying pending requests

- src/domain/friendship_event.rs
- src/ws/metrics.rs
- src/ws/service/friendships_service.rs
- src/ws/service/mapper/event.rs
Adds metric that counts the updates sent on subscription by event type.
```
dcl_social_service_rpc_updates_sent_on_subscription_total{event="cancel"} 1
dcl_social_service_rpc_updates_sent_on_subscription_total{event="request"} 1
```
> feat: counter updates sent on subscription

- src/domain/friendship_event.rs
- src/ws/app.rs
- src/ws/metrics.rs
- src/ws/service/friendships_service.rs
- src/ws/service/mapper/error.rs
- src/ws/service/mapper/event.rs
Add metric that counts the clients currently connected via Websocket
Closes #249 
```
dcl_social_service_rpc_connected_clients_total 2
```
-----
Adds metrics that collects the procedures call incoming and outgoing payload size.
Closes #253 
```
dcl_social_service_rpc_out_procedure_call_size_bytes_histogram_bucket{procedure="GetFriends",le="+Inf"} 71
dcl_social_service_rpc_out_procedure_call_size_bytes_histogram_sum{procedure="GetFriends"} 6390
dcl_social_service_rpc_out_procedure_call_size_bytes_histogram_count{procedure="GetFriends"} 71
```
```
dcl_social_service_rpc_in_procedure_call_size_bytes_histogram_bucket{procedure="GetFriends",le="+Inf"} 1
dcl_social_service_rpc_in_procedure_call_size_bytes_histogram_sum{procedure="GetFriends"} 90 …
```
> feat: add ws metrics

- src/api/routes/synapse/room_events.rs
- src/components/synapse.rs
- src/synapse/synapse_handler.rs
- src/ws/service/friendship_event_updates.rs
Join room in synapse when accepting a friend request according to Synapse Documentation
https://spec.matrix.org/legacy/r0.0.0/client_server.html#post-matrix-client-r0-rooms-roomid-join
> Add join event to synapse room

- src/entities/queries.rs
retrieve mutual friends only from active
> fix: mutuals query

- .github/workflows/docker-tag.yml
- src/api/routes/synapse/room_events.rs
- src/components/synapse.rs
- src/synapse/synapse_handler.rs
- src/ws/service/friendship_event_updates.rs
- tests/routes/matrix/room_events.rs
This PR solves a corner case when the matrix room already existed but one of the members didn't join. For example:
1. User A sends a friend request to User B: this creates a room in Matrix, where A is a member and sends an invite to B.
2. User A cancels the friend request (nothing is done in Matrix)
3. User B sends a friend request to User A: He needs to join the room first, as it already exists
> fix: Join room when sending a request too

- Dockerfile
Using the latest version of the Rust docker base image resulted in using Debian 12 while the run image was still using Debian 11 and that ended up in being unable to solve dependencies that required different versions
> fix: use debian11 as rust base docker image
