decentraland/social-service

src/metrics.rs
This PR:
- change metrics namespace
=> fix: change metrics namespace

.github/workflows/manual-deploy.yml
Add manual workflow to deploy to production
=> Add manual workflow to deploy to production

Cargo.lock, Cargo.toml, src/configuration.rs, src/lib.rs, src/middlewares/metrics_token.rs, src/middlewares/mod.rs, tests/health.rs, tests/helpers/server.rs, tests/metrics.rs
This PR: 
- add middleware to protect the `/metrics` endpoint
=> feat: add metrics middleware

.github/workflows/docker-latest.yml
After merging this PR every commit to main will be deployed to production
=> Add prod as deployment env

.github/workflows/test.yml, Cargo.lock, Cargo.toml, docker-compose.yml, src/components/app.rs, src/components/configuration.rs, src/components/mod.rs, src/components/redis.rs, tests/components/mod.rs, tests/components/redis.rs, tests/main.rs
This PR adds the Redis component that will be used for the token to user cache
=> feat: Add redis connection

src/components/app.rs
- Removes duplication between `AppComponents::default` and `AppComponents::custom` in favor of the later using `CustomComponents::default` with no custom components set.
- Refactors references of `AppComponents::*` to `Self::*` when in scope
=> refactor: remove default duplication

src/components/synapse.rs, src/components/users_cache.rs, src/middlewares/check_auth.rs, src/routes/synapse/handlers.rs, src/routes/synapse/room_events.rs, src/routes/v1/friendships/get.rs, src/routes/v1/friendships/mutuals.rs, tests/common/mod.rs, tests/component_users_cache.rs, tests/middleware_check_auth.rs, tests/route_synapse.rs, tests/routes/matrix/room_events.rs
fixes https://github.com/decentraland/social-service/issues/108
=> fix: Add social_user_id as another field

src/routes/synapse/room_events.rs, tests/routes/matrix/room_events.rs
fixes: https://github.com/decentraland/social-service/issues/113
=> fix: processing matrix addresses

Cargo.lock, Cargo.toml, src/components/synapse.rs, src/entities/friendship_history.rs, src/entities/friendships.rs, src/lib.rs, src/routes/synapse/room_events.rs, src/routes/v1/friendships/history.rs, src/routes/v1/friendships/mod.rs, src/routes/v1/friendships/types.rs, tests/component_database.rs, tests/routes/matrix/room_events.rs, tests/routes/v1/friendships/history.rs, tests/routes/v1/friendships/mod.rs, tests/routes/v1/friendships/utils.rs
=> feat: persist optional `body` param for friend requests

migrations/20230130202319_add-friendships-lower-index.down.sql, migrations/20230130202319_add-friendships-lower-index.up.sql, src/components/configuration.rs, src/entities/friendships.rs, src/entities/queries.rs, tests/component_database.rs, tests/routes/v1/friendships/get.rs, tests/routes/v1/friendships/mutuals.rs
fixes https://github.com/decentraland/social-service/issues/123
=> fix: handle friendships case insensitive

.github/dependabot.yml, README.md
Configure dependabot to run on Mondays to avoid having PRs that takes the attention from the work during the week days
=> chore: config dependabot to run at a fixed time

src/routes/v1/friendships/get.rs, tests/routes/v1/friendships/get.rs
fixes https://github.com/decentraland/social-service/issues/138
=> feat: support for friendships/me

src/lib.rs, tests/routes/v1/friendships/get.rs
fixes https://github.com/decentraland/social-service/issues/135
=> fix: allow trailing bar in endpoints

.github/workflows/clippy-checks.yml
=> chore: avoid running twice on PR build

build.rs, src/client.rs, src/components/database.rs, src/entities/friendships.rs, src/ws/service/friendships_service.rs
To return get all friends as stream use a stream query in the database
=> feat: fetch all friends in stream

src/components/database.rs, src/ws/app.rs, src/ws/service/friendships_service.rs
fixes https://github.com/decentraland/social-service/issues/176
fixes https://github.com/decentraland/social-service/issues/183
=> Add logs to rpc server

build.rs, src/entities/friendship_history.rs, src/entities/friendships.rs, src/entities/queries.rs, src/ports/users_cache.rs, src/ws/service/error.rs, src/ws/service/friendships_service.rs, src/ws/service/mod.rs, tests/component_database.rs, tests/ws/friendship_service.rs, tests/ws_service_friendship_service.rs
Implement the necessary logic to retrieve all the Friendships Request Events
```proto
// Get the list of request events for the authenticated user
rpc GetRequestEvents(Payload) returns (RequestEvents) {}
```
=> feat: retrieve friendship requests

Cargo.lock, Cargo.toml, build.rs, src/components/users_cache.rs, src/entities/friendship_history.rs, src/entities/friendships.rs, src/ws/app.rs, src/ws/service/database_handler.rs, src/ws/service/errors.rs, src/ws/service/friendship_event_updates.rs, src/ws/service/friendship_event_validator.rs, src/ws/service/friendship_status_calculator.rs, src/ws/service/friendships_service.rs, src/ws/service/mapper.rs, src/ws/service/synapse_handler.rs
Handle errors from FriendshipsServiceServer messages, including Internal Server Errors and Unauthorized errors.
=> feat: error handling

migrations/20230501194523_add-present-constraint-synapse-room-id-friendships.down.sql, migrations/20230501194523_add-present-constraint-synapse-room-id-friendships.up.sql
fixes: https://github.com/decentraland/social-service/issues/191
=> feat: add not null constraint to synapse_room_id in friendships

src/models/address.rs, src/models/mod.rs, src/ws/app.rs, src/ws/service/friendships_service.rs
fixes https://github.com/decentraland/social-service/issues/198
=> feat: Add EthAddress with case insensitive PartialEq

src/ws/service/friendships_service.rs
Fixes: https://github.com/decentraland/social-service/issues/215
=> Remove not necessary tokio::spawn

src/main.rs, src/ws/app.rs, src/ws/metrics.rs, src/ws/service/friendships_service.rs, tests/component_database.rs
Fixes #229 
```j son
dcl_social_service_rpc_procedure_call{procedure="GetFriends",code="OK"} 1
dcl_social_service_rpc_procedure_call{procedure="GetRequestEvents",code="OK"} 1
dcl_social_service_rpc_procedure_call{procedure="SubscribeFriendshipEventsUpdates",code="OK"} 1
dcl_social_service_rpc_procedure_call{procedure="UpdateFriendshipEvent",code="INTERNAL_SERVER_ERROR"} 2
```
=> chore: add procedure calls metric collector

.github/workflows/docker-latest.yml
This is temporary to run a migration in dev first
=> remove deploy automatically to prod

migrations/20230609183358_update-friendship-history-migrated.down.sql, migrations/20230609183358_update-friendship-history-migrated.up.sql
fixes https://github.com/decentraland/social-service/issues/242
=> fix: update accepted requests migrated from synapse

.github/workflows/docker-latest.yml
Reverts decentraland/social-service#247
=> Revert "remove deploy automatically to prod"

src/components/synapse.rs
Reverts decentraland/social-service#262
=> Revert "Fix mapping synapse response"

src/ws/app.rs, src/ws/metrics.rs, src/ws/service/friendships_service.rs
Implement `connection_duration_histogram_collector: Histogram` metric
fixes: https://github.com/decentraland/social-service/issues/250
=> feat: histogram connection duration

src/domain/friendship_event.rs, src/ws/app.rs, src/ws/metrics.rs, src/ws/service/friendships_service.rs, src/ws/service/mapper/error.rs, src/ws/service/mapper/event.rs
Reverts decentraland/social-service#251
=> Revert "feat: add ws metrics"

build.rs, src/entities/friendships.rs, src/entities/queries.rs, src/ws/metrics.rs, src/ws/service/friendships_service.rs
depends on https://github.com/decentraland/protocol/pull/158
=> feat: implement mutual friends in social server
